### ISSUE TITLE
[Bug 🐛]: Go get + go mod tidy fails

### ISSUE THREAD

**Issue by wood-jp** [BooleanCat/go-functional#148]
**What happened?**

main.go:
```
package main

import (
	"fmt"
	fn "github.com/BooleanCat/go-functional/v2"
)

func main() {
	for i := range fn.Integers[int](3, 10, 2) {
		fmt.Println(i)
	}
}
```
command-line:
```
$ go mod init
$ go mod tidy
go: finding module for package github.com/BooleanCat/go-functional/v2
go: github.com/wood-jp/iterator_testing imports
	github.com/BooleanCat/go-functional/v2: module github.com/BooleanCat/go-functional/v2@latest found (v2.3.0), but does not contain package github.com/BooleanCat/go-functional/v2
```

**What did you expect to happen?**

No errors.

**Which version of go-functional were you using?**

```
go version go1.23.1 linux/amd64
```

**To Reproduce**

Provided

**Do you intend to fix this issue yourself?**

No

**Additional context**

Happy for this to be user error, but looks broken to me.

**Comment by BooleanCat** [comment]
Hi there! 

In your import statement you're missing the package name `it` at the end. 

```go
package main

import (
	"fmt"
	"github.com/BooleanCat/go-functional/v2/it"
)

func main() {
	for i := range it.Integers[int](3, 10, 2) {
		fmt.Println(i)
	}
}
```

**Comment by wood-jp** [comment]
@BooleanCat Amazing, thanks. I would suggest you add that to your main README though as it certainly wasn't clear to me (and I use go in my professional work daily).
