### ISSUE TITLE
[Proposal] Iterator over chan

### ISSUE THREAD

**Issue by dranikpg** [BooleanCat/go-functional#17]
I think that having an iterator over a channel would be very convenient, as it would allow to build delayed pipelines.
Maybe even not only over one channel, but over multiple. The reflect package has a dynamic select to listen to multiple channels. 

Another idea would be a function for consuming an iterator and sending all its values to a channel.
This way we could describe a pipeline that reads from a channel, does some mapping/filtering and writes to another. All imperatively 🥳 

I'm eager to implement it. What do you think of it?

**Comment by BooleanCat** [comment]
Thanks for the suggestion, I like the idea. What do you imagine using it would look like (as a code snippet)?

What would be a use case for an iterator that listens to multiple channels at once?

**Comment by BooleanCat** [comment]
I've created a new feature request template - if it's not too much trouble would you mind re-submitting this issue and answering the questions in the template? https://github.com/BooleanCat/go-functional/issues/new/choose

Thanks!

**Comment by BooleanCat** [comment]
I've moved this issue over to #29 - I'll be closing this one. Thanks for the suggestion!
