### ISSUE TITLE
Just a friendly comment about documentation

### ISSUE THREAD

**Issue by nitram509** [BooleanCat/go-functional#2]
Hi,

I stumbled upon your project via Twitter and while I read your TODOs in your README,
this echoed with me since I'm writing a go library as well.
I also searched for simple ways, to include example code in the README,
which is automatically checked by the compiler and I would like to avoid manual copy&paste actions.

May I share my solution?
* using Go's support for examples: name your file like "example_*_test.go". This will be compiled during 'go test' run and will not be compiled into production code. See also https://go.dev/doc/effective_go#package-names
* using Markdown-Autodocs github action, which replaces placeholders in your REAME.md with the actual example file ode (see also dineshsonachalam/markdown-autodocs@v1.0.4)

I hope this saves you some research time, as I found this very helpful for my own library 'lib-bpmn-engine'.

👍 for you and your project.

PS: not an issue, this can be closed.

**Comment by BooleanCat** [comment]
Thanks so much for the pointers!
