### ISSUE TITLE
[Feature 🔨]: Offer commutative built in operators in the "ops" package

### ISSUE THREAD

**Issue by BooleanCat** [BooleanCat/go-functional#22]
**Is your feature request related to a problem? Please describe.**

I can imagine using the built in operators (see [this list](https://yourbasic.org/golang/operators/)) in iterators like `Map` or collectors like `Fold` as a common use case. Some operators are commutative (the order of argument does not matter) whilst others are not. I'm not yet convinced of the value of providing non-commutative operators so am considering those out of scope for this feature request.

Currently users of `Map`-like iterators or `Fold`-like collectors would have to define these themselves.

**Describe the solution you'd like**

Offer the following operators to users of `go-functional` via the `ops` package:

- Sum (`+`)
- Product (`*`)
- BitwiseAnd (`&`)
- BitwiseOr (`|`)
- BitwiseXor (`^`)

**Provide code snippets to show how this new feature might be used.**

```go
func ExampleSum() {
  fmt.Println(iter.Fold[string](iter.Lift([]{"hello ", "there"}), "", ops.Sum[string]))
  // Output: hello there
}
```

```go
func ExampleProduct() {
  fmt.Println(iter.Fold[int](iter.Lift([]{1, 2, 3, 4}), 1, ops.Product[int]))
  // Output: 24
}
```

```go
func ExampleBitwiseAnd() {
  fmt.Println(iter.Fold[int](iter.Lift([]{1, 3}), 1, ops.BitwiseAnd[int]))
  // Output: 1
}
```

```go
func ExampleBitwiseOr() {
  fmt.Println(iter.Fold[int](iter.Lift([]{1, 3}), 0, ops.BitwiseOr[int]))
  // Output: 3
}
```

```go
func ExampleBitwiseXor() {
  fmt.Println(iter.Fold[int](iter.Lift([]{1, 3}), 0, ops.BitwiseXor[int]))
  // Output: 2
}
```

**Does this incur a breaking change?**

Yes.

**Do you intend to build this feature yourself?**

No - I'd like to offer this out to folks who wish to practice Go or open-source contribution.

**Additional context**

Within the `ops` package there is already a `Add` operation. This should be renamed to `Sum` and incurs a breaking change (which is fine since we're not at version 1.0.0 yet.

**Comment by BooleanCat** [comment]
@dranikpg What do you think about the value of offering non-commutative operators within the `ops` package (such as `-` or `/`)?

It's not in scope for this issue but I'm considering opening another feature issue to include these too.

**Comment by seiyab** [comment]
Perhaps associativity is more important than commutativity.

**Comment by seiyab** [comment]
@BooleanCat 
I'm considering to work with it.
The examples doesn't have the `initial` argument for the `Fold` function.
Which one is true?
- You mistyped.
- You are going to omit `initial`. `Fold` will panic with empty iterators.
- You are going to omit `initial`. `Fold` will return "zero" value (in context of Golang) for empty iterators.
- You are going to omit `initial`. `Fold` will return "zero" (in context of monoid) for empty iterators. The operators shouldn't have only operation but also zero (`mempty` in Haskell)

**Comment by BooleanCat** [comment]
Thanks @seiyab I've added in the missing arguments.
