### ISSUE TITLE
[Feature 🔨]: Iterator from channel

### ISSUE THREAD

**Issue by BooleanCat** [BooleanCat/go-functional#29]
**Is your feature request related to a problem? Please describe.**

A common way to do transformation pipelines currently is using channels. It would be useful to be able to plug into those.

**Describe the solution you'd like**

An iterator that plugs consumes a channel. The iterator is exhausted when the channel is closed.

**Provide code snippets to show how this new feature might be used.**

```go
func ExampleFromChannel() {
  ch := make(chan int, 2)

  go func() {
    ch <- 1
    ch <- 2
    close(ch)
  }()

  fmt.Println(iter.Collect[int](iter.FromChannel[int](ch)))

  // Output: [1 2]
}
```

**Does this incur a breaking change?**

No.

**Do you intend to build this feature yourself?**

No.

**Additional context**

N/A.

**Comment by prycey77** [comment]
I'd like to pick this up if that's ok.

**Comment by BooleanCat** [comment]
Sure @prycey77 , thanks!

**Comment by BooleanCat** [comment]
For reference, I've implemented `ToChannel` in the `iter` package.
