### ISSUE TITLE
[Feature 🔨]: Generator

### ISSUE THREAD

**Issue by seiyab** [BooleanCat/go-functional#31]
**Is your feature request related to a problem? Please describe.**

No, just an idea.
It should be convenient because this pattern can be seen in other languages.
examples: [Python](https://docs.python.org/3/glossary.html#term-generator-iterator), [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator), [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/-sequence-scope/)

**Describe the solution you'd like**

Creating iterator from imperative function.

**Provide code snippets to show how this new feature might be used.**

```go
func ExampleGenerator() {
  it := iter.Generator[string](func(yield func(v string)) {
    yield("hello")
    yield("generator")
  })
  fmt.Println(iter.Collect(it))
  // Output: [hello generator]
}
```

**Does this incur a breaking change?**

no.

**Do you intend to build this feature yourself?**

Maybe.
Feel free to comment if someone intend to commit.

**Additional context**
I'm not sure whether it is good feature or not.
It's because following reasons.
- It is imperative rather than functional.
- The functionality can be nearly achieved by #29 . 

Justifications exist, but weak.
- It bridges gaps between imperative and functional.
- It is a bit clear and readable.

**Comment by seiyab** [comment]
function name can be `FromProcedure`, `FromRoutine` `FromFunction`, `Go` or something else

**Comment by dranikpg** [comment]
This is definitely an interesting feature.

> Justifications exist, but weak.

Contrary to iterators from channels, this one has no overhead and should be preferred if you don't work with concurrency/plug into existing code.

An important counterpoint to having this feature is that the same functionality can be achieved with a custom iterator. You just need a struct and a Next function. This might me impractical given that you have to store your "local" variables in your struct, but is not really that verbose.

I'd take this on up, if @BooleanCat sees this feature as viable

**Comment by seiyab** [comment]
@dranikpg 
Thank you for your helpful comment.
> In case the iterator is dropped and not exhausted, the spawned goroutine will stay around forever

That's true.
So feasible options are following, and each of them has clear disadvantages.

1. using `chan T`, `chan any` (for interrupt) and explicit `Close` method
     - ```go
        func ExampleGenerator() {
          it := iter.Generator[string](func(yield func(v string) bool) {
            if !yield("hello") { return }
            if !yield("generator") { return }
          })
          defer it.Close()
          fmt.Println(iter.Collect(it))
          // Output: [hello generator]
        }
       ```
    - disadvantages
        - need explicit `Close`
        -  the lifecycle might be complex when it is wrapped by higher-order iterators.
        - need to check the result of `yield`
        - it might be better that this functionality is provided by another package for utility of `chan` and then just wrap it by `ChanIter`.
2. using `T[]`
    - ```go
      func Generator[T any](f func(yield func(v T)))*LiftIter[T] {
        var items []T
        yield := func(v T) {
          items = append(items, v)
        }
        f(yield)
        return Lift(items)
      }
      ```
    - disadvantages
        - non-lazy evaluation is unexpected and confuses developer
        - it cannot handle infinite iterator
3. in-place `Next`
    - ```go
      func ExampleGenerator() {
        it := iter.Generator[int](func() func() int {
          var i int = 1
          return func() int {
            r := i
            i *= 2
            return r
          }
        })
        fmt.Println(iter.Collect(iter.Take(it, 3)))
        // Output: [1 2 4]
      }
      ```
    - disadavantage
        - the API is far from generator. it might be better to implement as plain custom Iterator as you mentioned first.

As far as I know, this suggestion can't be useful enough.
I will close this issue if there is no good idea.

**Comment by dranikpg** [comment]
I'm afraid the won't be any more ideas 😢 

The first option is not that bad actually, except for the `Close`. Having to close the iterator is  ~~inconvenient~~ almost impossible, especially if you want to pass it around and wrap it up further.

The third option is usable. Instead of passing a function returning a closure, we could just directly pass the closure. If someone needs local state, he can just create this helper function on its own or store it directly in the function using the iterator.

```go
func CreateMagicSequence(offset int) Iterator[int] {
  r := rand.New()
  return Generator[int](func(index int) Option[int] {
    return Option.Some(index * r.Intn(10) + offset)
  }
}
```

This still more compact than defining your own type + contructor + `Next()` function.

**Comment by BooleanCat** [comment]
I like this option too, where the Generator is a simple convenience for a stateless Iterator (or where state is captured through a closure). Unlike @dranikpg I think the Generator input signature should match that of `Next()` (without the receiver):

```go
func Generator[T any](func() option.Option[T]) GeneratorIter { ... }
```

**Comment by seiyab** [comment]
Passing a closure directly sounds good.
I prefer the signature that matches that of `Next()`.

Perhaps the name `Generator` is confusing for current idea?

**Comment by BooleanCat** [comment]
Perhaps simply `iter.New(f) *FuncIter { ... }`

**Comment by BooleanCat** [comment]
Maybe hold fire on this until the Go iterator conversation comes to fruition.

https://github.com/golang/go/issues/61897

**Comment by BooleanCat** [comment]
Well Go iterators are a thing soon! I think an API like this would be appropriate:


```go
func Generator[V any](fn func() V) iter.Seq[V] {
  ...
}

and

func Generator2[V, W any](fn func() (V, W)) iter.Seq2[V, W] {
  ...
}
```

Note that the current latest implementation is in the branch `v2`.

Not sure if you're still interested in working on this @seiyab ?

**Comment by seiyab** [comment]
Thank you for notifying me!
Feel free to implement it. I'm still interested in this but I'm busy for a while because of my life event. I might work on it when I will get time.

**Comment by BooleanCat** [comment]
I don't think this is needed any longer given the new `iter.Seq` syntax. Happy to revisit if there's a need for it from users.
