### ISSUE TITLE
[Feature 🔨]: Add `option.Map`

### ISSUE THREAD

**Issue by MSE99** [BooleanCat/go-functional#33]
**Is your feature request related to a problem? Please describe.**

It's a feature request, a lot of std libs of functional programming languages have this built in.

**Describe the solution you'd like**

A robust implementation of the `option.Map`

**Provide code snippets to show how this new feature might be used.**

Given the following function

```golang
func x (int) string {
  if x == 0 {
    return "zero"
  }

  return "non-zero"
}
```

We should be able to pass function `x` to `option.Map`

```golang
option.Map[int, string](x)
```

and get back a closure `y`

```golang
func y (o option.Option[int]) option.Option[string] {
  if o.IsNone() {
    return option.None[string]()
  }

  return option.Some[string](x(o.Unwrap())
}
``` 

Effectively `Map` allows a function to work with option types, it's pretty useful when we want functions to more easily
work with functions that return an `Option` variant

**Does this incur a breaking change?**

No, it does not.

**Do you intend to build this feature yourself?**

Yes, it should be pretty simple.

**Comment by BooleanCat** [comment]
Hi there, thanks for your thoughts.

This looks good to me, happy to receive a PR.
