### ISSUE TITLE
Lawyer wants to pay 50 USD to have this issue fixed

### ISSUE THREAD

**Issue by tvbot20** [BooleanCat/go-functional#70]
I am willing to pay 50 USD if you resolve this issue https://github.com/BooleanCat/go-functional/issues/60 by 27th August 
 For more details visit [https://mintycode.io](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=c6b95d08-c8c0-4d2b-b1dc-e27d8f92eea5&owner=booleancat&name=go-functional)

**Comment by BooleanCat** [comment]
For context on this, I met someone at a founders' meetup who pitched this product to me as maintainer and I said I'd try it out.

**Comment by BooleanCat** [comment]
I decided against this because I didn't want to think just yet about:

1. What are my tax implications of this?
2. What if someone else completes the issue, or partially completes it?
3. Should all contributors share this?
