### ISSUE TITLE
[Bug 🐛]: Run report card linters in `make lint`

### ISSUE THREAD

**Issue by BooleanCat** [BooleanCat/go-functional#77]
**What happened?**

Sometimes go-functional fails a [report card lint](https://goreportcard.com/report/github.com/BooleanCat/go-functional) (misspell has been an example). I only learn about this *after* I ship a new release.

**What did you expect to happen?**

I'd like linting to fail in CI if go-functional scores anything less than 100% on the report card linters.

**Which version of go-functional were you using?**

`v0.15.0`

**To Reproduce**

You can see lint errors on the report card (if there are any currently).

**Do you intend to fix this issue yourself?**

No.

**Additional context**

I suspect these are probably optional linters in `golangci-lint` and it's just a case of configuring a yaml file in the repo. If that is the case, run all default linters + linters run in the report card. Adding additional linters is out of scope but I would consider a separate PR with solid reasoning for using other linters.

**Comment by mrchocha** [comment]
Hi @BooleanCat, I would like to work on this issue.
