### ISSUE TITLE
[Feature 🔨]: Partial JSON support for result.Result

### ISSUE THREAD

**Issue by BooleanCat** [BooleanCat/go-functional#79]
**Is your feature request related to a problem? Please describe.**

It's not clear to me how a a result should be marshalled into JSON when it holds an error value (since error is represented by an interface). Type information regarding the error would be lost.

However, it seems reasonable to me to support Unmarshal of plain values into result.Result[T] since they will always be unmarshalled into `result.Ok` variants.

**Describe the solution you'd like**

Support unmarshalling of values into `result.Result[T]`. For example the JSON value `42` should unmarshall into:

```go
result.Ok(42)
```

**Does this incur a breaking change?**

No.

**Do you intend to build this feature yourself?**

Maybe.

**Additional context**

Do not implement marshalling, only unmarshalling.

**Comment by BooleanCat** [comment]
See https://github.com/BooleanCat/go-functional/blob/main/option/json.go for a similar example.

**Comment by myusko** [comment]
@BooleanCat I'd like to work on the issue
