### ISSUE TITLE
[Feature 🔨]: String representations for all iterators

### ISSUE THREAD

**Issue by BooleanCat** [BooleanCat/go-functional#81]
**Is your feature request related to a problem? Please describe.**

Printing as a string today (`0.17.0`) looks ugly:

```go
counter := iter.Count()
fmt.Println(counter)
fmt.Printf("%s\n", counter)
// &{{%!s(*iter.CountIter=&{{0xc0000a6000} 0})} %!s(int=0)}
```

This makes it hard to debug issues when you need to print iterators.

**Describe the solution you'd like**

Implement the stringer interface for each iterator. The text should make it clear that it's an iterator and the kind of iterator that it is. Perhaps something like:

```go
fmt.Printf("%s\n", iter.Count())  // Iterator<Count>
fmt.Printf("%s\n", iter.Count().Take(4)) // Iterator<Take>
```

I'm open to better ideas about how it should be represented.

**Provide code snippets to show how this new feature might be used.**

The `fmt.Stringer()` interface should be implemented for each iterator.

**Does this incur a breaking change?**

No.

**Do you intend to build this feature yourself?**

Maybe.

**Additional context**

Doesn't all need to be in one PR, I'd accept a PR for 1+ iterators. This issue is closed when all are implemented.

**Comment by BooleanCat** [comment]
Another idea:

```go
func (iter ChainIter[T]) String() string {
	var zero [0]T
	tt := reflect.TypeOf(zero).Elem()

	return fmt.Sprintf("Iterator(name=Chain, type=%s)", tt)
}

var _ fmt.Stringer = ChainIter[struct{}]{}

fmt.Printf("%s", iter.Chain[int]())
// Iterator(name=Chain, type=int)
```

**Comment by BooleanCat** [comment]
Or possibly "yields=" rather than "type="

**Comment by myusko** [comment]
I'll work on the issue, also going to play with formats.

**Comment by myusko** [comment]
I hope that in the next 2-3 weeks, I'll start work on it.

**Comment by myusko** [comment]
@BooleanCat I revisited our approaches to the `Map` stringer implementation, and maybe, it would also be cool to consider the next format `Iterator<Map, args(in=int, out=string)` or something like that, what do you think?

We explicitly identify in the string representation what type of input/output will be, e.g `in=..., out=...`

**Comment by BooleanCat** [comment]
@myusko I'm closing this becasue it's no longer relevant for the V2 API.
