### ISSUE TITLE
[Feature 🔨]: Create a new function by chaining existing ones

### ISSUE THREAD

**Issue by KytnaCode** [BooleanCat/go-functional#87]
**Is your feature request related to a problem? Please describe.**

It is a feature that I liked a lot from the IBM/fp-go library, but that library is very confusing to use and has hardly any documentation.

**Describe the solution you'd like**

Create a function that takes an initial value t0 and successively applies N functions where the input of a function is the return value of the previous function.

**Provide code snippets to show how this new feature might be used.**

```go
// example implementation
func Flow2[F1 ~func(T0) T1, F2 ~func(T1) T2, T0, T1, T2 any](f1 F1, f2 F2) func(T0) T2 {
	return func(t0 T0) T2 {
		return f2(f1(t0))
	}
}

var (
	toStr = func(value int) string { return fmt.Sprint(value) }
	length = func(value string) int { return len(value) }
)

func main() {
	// usage
	myFun := Flow2(toStr, length)
	
	// first convert int to string, then get the length of the string
	
	fmt.Println(myFun(123456)) // 6
}

```

**Does this incur a breaking change?**

No.

**Do you intend to build this feature yourself?**

Yes

**Additional context**

My English is quite bad, so I could not do the documentation of the feature, but I could use a translator to leave notes for whoever is going to do the final documentation.

**Comment by BooleanCat** [comment]
Thanks for the idea!

I've given this some thought and I wouldn't accept this change into go-functional. I'm pretty keen to keep numbered functions like `Flow2` and similar names out of go-functional. I might perhaps have accepted a PR for something like `Flow(f1, f2, f3, f4, ...)` (i.e. with a variadic argument list) but Go's limited type system for generics makes this impossible.

Most utility functions in go-functiona centre around being helpful for iterators in some way, and the same can be achived by using multiple `Map` iterators.
